name: debt_visualizer
description: A debt visualization and management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  provider: ^6.0.5
  fl_chart: ^0.63.0
  intl: ^0.18.1
  supabase_flutter: ^2.8.4
  flutter_secure_storage: ^9.0.0
  in_app_purchase: ^3.1.11
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

assets:
  - .env
